set(ENUM_TARGETS BOOST_SINGLETON)

set(BUILD_FEATURES
	MIN_VERSION SCALAR VERSION 1.68.0
	COMPONENTS VECTOR STRING ""
)

set(FILE_OPTIONS
	NICE_NAME "Boost library"
	DONT_LINK_TO_DEPENDEE
	NO_TARGETS
	SINGLETON_TARGETS
)

