set(ENUM_TEMPLATES GENERATE_EXPORT_HEADER)

set(TARGET_PARAMETERS 
	EXPORT_FILE_NAME	SCALAR	STRING "${CMAKE_BINARY_DIR}/${PROJECT_NAME}/${PROJECT_NAME}_export.h"
	PROJECT_NAME SCALAR STRING "${CMAKE_PROJECT_NAME}"
)

set(TARGET_LINK_PARAMETERS
	SHARED OPTION BOOL "OFF"
)

set(TEMPLATE_OPTIONS
	NO_TARGETS
)

function(apply_dependency_to_target DEPENDEE_TARGET_NAME OUR_TARGET_NAME)
	include( GenerateExportHeader )
	message(STATUS "generate_export_header( ${DEPENDEE_TARGET_NAME} EXPORT_FILE_NAME \"${EXPORT_FILE_NAME}\" )")
	generate_export_header( ${DEPENDEE_TARGET_NAME} BASE_NAME ${CMAKE_PROJECT_NAME} EXPORT_FILE_NAME "${EXPORT_FILE_NAME}" )
	
	if(SHARED)
		target_compile_definitions(${DEPENDEE_TARGET_NAME} "${DEPENDEE_TARGET_NAME}_STATIC_DEFINE")
	endif()
	target_include_directories(${DEPENDEE_TARGET_NAME} PUBLIC ${CMAKE_BINARY_DIR})
endfunction()

